services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile
    #image: ubuntu:22.04
    container_name: ansible-controller
    hostname: controller
    command: bash
    stdin_open: true
    tty: true
    volumes:
      - ./hosts:/home/ansible/hosts
      - ./playbooks:/playbooks
      - ./meu_primeiro_playbook.yml:/home/ansible/meu_primeiro_playbook.yml
      - ./index.html.j2:/home/ansible/index.html.j2
    networks:
      - ansible-net

  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    hostname: node1
    networks:
      - ansible-net

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    hostname: node2
    networks:
      - ansible-net

  node3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node3
    hostname: node3
    networks:
      - ansible-net

networks:
  ansible-net:
    driver: bridge

